/* Generated By:JavaCC: Do not edit this line. S3_10TreeConstants.java Version 7.0.9 */
public interface S3_10TreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTDECL = 1;
  public int JJTATTRICONST = 2;
  public int JJTATTRIEXPR = 3;
  public int JJTEXPR = 4;


  public String[] jjtNodeName = {
    "Expression",
    "Decl",
    "AttriConst",
    "AttriExpr",
    "Expr",
  };
}
/* JavaCC - OriginalChecksum=31ae015ab9dbb08c6d9d1fe7578db371 (do not edit this line) */
