/* Generated By:JJTree&JavaCC: Do not edit this line. S3_10Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S3_10Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int IDENT = 6;
  /** RegularExpression Id. */
  int VIRG = 7;
  /** RegularExpression Id. */
  int PVIRG = 8;
  /** RegularExpression Id. */
  int CONST = 9;
  /** RegularExpression Id. */
  int IGUAL = 10;
  /** RegularExpression Id. */
  int MULT = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"int\"",
    "<IDENT>",
    "\",\"",
    "\";\"",
    "<CONST>",
    "\"=\"",
    "\"*\"",
  };

}
