/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.9 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;
  public int JJTARITM = 4;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
    "Aritm",
  };
}
/* JavaCC - OriginalChecksum=ab7fb8e1a05bd2e5c7343e40af32d110 (do not edit this line) */
